spring:
  application:
    name: notification-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/notification-db
    username: abbes
    password: abbes
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka