version: '3'

volumes:
  keycloak-db-data:
  admin-db-data:
  pgadmin-data:

services:
  keycloak-db:
    image: postgres
    container_name: keycloak-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8088:8080"
    depends_on:
      - keycloak-db
  admin-service-db:
    image: postgres
    container_name: admin-service-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin-db
      POSTGRES_USER: abbes
      POSTGRES_PASSWORD: abbes
    volumes:
      - admin-db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abbes@kyrios.dz
      PGADMIN_DEFAULT_PASSWORD: abbes
    volumes:
      - pgadmin-data:/var/lib/pgadmin