spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: admin-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8088/auth/realms/erp-dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/admin-db
    username: abbes
    password: abbes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        session_factory:
          interceptor: dz.kyrios.adminservice.config.auditlog.EntityChangeInterceptor
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: auditLogTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.addtypeheaders: false
        spring.json.type.mapping: userCreatedEvent:dz.kyrios.adminservice.event.user.UserCreatedEvent,event:dz.kyrios.adminservice.config.auditlog.EntityTrace,notificationEvent:dz.kyrios.adminservice.event.notification.NotificationPayload,notificationPlaceHolder:dz.kyrios.adminservice.event.notification.PlaceHolder
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

app:
  realm: erp-dev
  auth-server-url: http://localhost:8088/auth
  admin-client-id: account-service
  admin-client-secret: koO36nzQ0igdaMpA3byMRGpma0Biuufz