spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: admin-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/admin-db
    username: abbes
    password: abbes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        session_factory:
          interceptor: dz.kyrios.adminservice.config.auditlog.EntityChangeInterceptor
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: auditLogTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:dz.kyrios.adminservice.config.auditlog.EntityTrace
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

#keycloak:
#  ssl-required: external
#  auth-server-url: http://localhost:8088/auth
#  realm: erp-dev
#  resource: admin-service

app:
  realm: erp-dev